### ISSUE TITLE
cargo install issue 

### ISSUE THREAD

**Issue by dt665m** [chevdor/srtool-cli#15]
Currently, building on my local setup is failing on a new beta version of clap.

## Reproduce 8/18/21
OS: MacOS
Rust: 1.53.0

```sh
cargo install --git https://github.com/chevdor/srtool-cli
```

## Error
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /Users/macdenis/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.4/src/lib.rs:8:10
  |
8 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `clap`

**Comment by chevdor** [comment]
Thanks for the report @dt665m.
I just tested and I confirm getting the save problem when using rustc 1.53.0.
It works fine using rustc 1.54.0 though. I will check if I can fix that for 1.53.0.

**Comment by chevdor** [comment]
So obviously, the easiest would be to upgrade to rustc 1.54.0.
However, if you **have to** use 1.53.0, you can install using:
```
cargo install --locked --git https://github.com/chevdor/srtool-cli
```

**Comment by chevdor** [comment]
NOTE: the solution above is only valid as long as [this](https://github.com/chevdor/srtool-cli/blob/master/cli/Cargo.toml#L21) remains `3.0.0-beta.2`.

I can hold off to upgrading for a while but utlimately this will upgraded at some point. Newer version of clap beta (`>= 3.0.0-beta.3`) require rustc 1.54.0+.
